# Change these first
owner: vinkashq # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Vinkas
    url: https://vinkas.com/up
  - name: Vinkas Community
    url: https://community.vinkas.com/srv/status
  - name: Vinkas Blog
    url: https://blog.vinkas.com
  - name: Singfuse
    url: https://singfuse.com/up
  - name: Singfuse Forum
    url: https://forum.singfuse.com/srv/status
  - name: Singfact
    url: https://singfact.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://pcdn.vinkas.com/images/logo-black-512h.png
  name: Vinkas Status
  introTitle: "Uptime status of all the websites of Vinkas"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/vinkashq/upptime) to manage uptime data in GitHub Actions, Issues, and Pages.
  navbar:
    - title: Community
      href: https://community.vinkas.com
    - title: Blog
      href: https://blog.vinkas.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
